redCities = ["Beijing", "Seoul", "Tokyo", "Shangai", "Osaka", "Hong Kong", "Taipei", "Bangkok", "Ho Chi Minh City",
             "Manila", "Jakarta", "Sydney"]
blackCities = ["Algiers", "Istanbul", "Moscow", "Cairo", "Baghdad", "Tehran", "Riyadh", "Karachi", "Delhi", "Mumbai",
               "Kolkata", "Chennai"]
blueCities = ["San Francisco", "Chicago", "Montreal", "Atlanta", "Washington", "New York", "London", "Madrid", "Essen",
              "St. Petersburg", "Paris", "Milan"]
yellowCities = ["Los Angeles", "Mexico City", "Miami", "Bogota", "Lima", "Sao Paulo", "Lagos", "Kartoum", "Kinshasa",
                "Johannesburg", "Santiago", "Buenos Aires"]

adjList = [["San Francisco", "Chicago", "Los Angeles", "Manila", "Tokyo"],
           ["Chicago", "Montreal", "Atlanta", "Mexico City", "Los Angeles", "San Francisco"],
           ["Montreal", "Chicago", "New York", "Washington"],
           ["New York", "London", "Madrid", "Washington", "Montreal"],
           ["Washington", "Montreal", "New York", "Atlanta"],
           ["Atlanta", "Washington", "Miami", "Chicago"],
           ["London", "Essen", "Paris", "Madrid", "New York"],
           ["Madrid", "London", "Paris", "Algiers", "Sao Paolo", "New York"],
           ["Paris", "Essen", "Milan", "Algiers", "Madrid", "London"],
           ["Essen", "St Petersburg", "Milan", "Paris", "London"],
           ["Milan", "Essen", "Istanbul", "Paris"],
           ["St Petersburg", "Moscow", "Istanbul", "Essen"],
           ["Los Angeles", "Chicago", "Mexico City", "Sydney", "San Francisco"],
           ["Mexico City", "Chicago", "Miami", "Bogota", "Lima", "Los Angeles"],
           ["Miami", "Washington", "Bogota", "Mexico City", "Atlanta"],
           ["Bogota", "Miami", "Sao Paolo", "Buenos Aires", "Lima", "Mexico City"],
           ["Lima", "Bogota", "Santiago", "Mexico City"],
           ["Santiago", "Lima"],
           ["Sao Paolo", "Madrid", "Lagos", "Buenos Aires", "Bogota"],
           ["Buenos Aires", "Sao Paolo", "Bogota"],
           ["Lagos", "Khartoum", "Kinshasa", "Sao Paolo"],
           ["Kinshasa", "Khartoum", "Johannesburg", "Lagos"],
           ["Khartoum", "Johannesburg", "Kinshasa", "Lagos", "Cairo"],
           ["Johannesburg", "Khartoum", "Kinshasa"],
           ["Algiers", "Istanbul", "Cairo", "Madrid", "Paris"],
           ["Istanbul", "St Petersburg", "Moscow", "Baghdad", "Cairo", "Algiers", "Milan"],
           ["Cairo", "Istanbul", "Baghdad", "Riyadh", "Khartoum", "Algiers"],
           ["Moscow", "Tehran", "Istanbul", "St Petersburg"],
           ["Baghdad", "Tehran", "Karachi", "Riyadh", "Cairo", "Istanbul"],
           ["Riyadh", "Karachi", "Cairo", "Baghdad"],
           ["Tehran", "Delhi", "Karachi", "Baghdad", "Moscow"],
           ["Karachi", "Delhi", "Mumbai", "Riyadh", "Baghdad", "Tehran"],
           ["Mumbai", "Delhi", "Chennai", "Karachi"],
           ["Delhi", "Kolkata", "Chennai", "Mumbai", "Karachi", "Tehran"],
           ["Chennai", "Kolkata", "Bangkok", "Jakarta", "Mumbai", "Delhi"],
           ["Kolkata", "Hong Kong", "Bangkok", "Chennai", "Delhi"],
           ["Bangkok", "Hong Kong", "Ho Chi Minh City", "Jakarta", "Chennai", "Kolkata"],
           ["Jakarta", "Bangkok", "Ho Chi Minh City", "Sydney", "Chennai"],
           ["Beijing", "Seoul", "Shanghai"],
           ["Shanghai", "Seoul", "Tokyo", "Hong Kong", "Beijing"],
           ["Hong Kong", "Taipei", "Manila", "Ho Chi Minh City", "Bangkok", "Kolkata", "Shanghai"],
           ["Ho Chi Minh City", "Hong Kong", "Manila", "Jakarta", "Bangkok"],
           ["Seoul", "Tokyo", "Shanghai", "Beijing"],
           ["Taipei", "Osaka", "Manila", "Hong Kong", "Shanghai"],
           ["Manila", "San Francisco", "Sydney", "Ho Chi Minh City", "Hong Kong", "Taipei"],
           ["Sydney", "Los Angeles", "Jakarta", "Manila"],
           ["Tokyo", "San Francisco", "Osaka", "Shanghai", "Seoul"],
           ["Osaka", "Taipei", "Tokyo"]]
